////
Purpose
-------

Activities
------
Provide a single-line summary for each activity performed on a given day.  The
recommended format is "<summary><verb>", where "summary" is a brief description
of the activity, and "verb" is either "started", "progressed" or "completed".
This will help to capture tasks which span multiple days.

When an activity correlates with a task from the Statement of Work, try to use
the same verbiage as in the SOW to describe it.  This will greatly simplify
later reviews of this document.

Use good judgment when deciding which activities to list and which to omit.
A good starting point is to add:
- Any activity which requires 30 minutes or more to complete
- Tasks which are foundational or critical to the engagement regardless of time
  required
- Tasks which were not part of the Statement of Work but added per customer
  request

It is strongly recommended that the consultant update this part of the CER on a
daily basis to ensure all significant activity is captured.

Blockers
------
Provide a single-line summary for each blocker present in a given day.   The
recommended format is "<summary><verb>" where "summary" is a brief description
of the activity and "verb" is either "encountered", "ongoing" or "resolved".
This will help to capture the duration and impact of blockers.

Try to refrain from detailed explanations of blockers in this section.  Place
relevant details in the "Challenges" area of the CER and try to use the first
sentence of the Challenge description as the summary here.

PROTIP: Avoid duplication of effort with project status reports.  
If a delivery team elects to use the optional "Daily Journal" component in the 
CER then those updates should be used by the Project Manager to compile updates 
for the project status report. If the "Daily Journal" is not in use then 
information for the status report will be provided separately to the 
Project Manager by the Consultant/Architect(s) on the engagement. 

For more information see:  CER Best Practices - https://source.redhat.com/groups/public/kmo/engagementjournalstandardization/consulting_engagement_report_cer_wiki/cer_best_practices
and Delivering the CER - https://source.redhat.com/groups/public/kmo/engagementjournalstandardization/consulting_engagement_report_cer_wiki/delivering_the_cer 

Sample
------

[cols="1,5,5",options=header]
|===
|Date
|Activities
|Blockers/Next Plan

// Date
| 06/05/2021

// Activities
a|
- Primary cluster deployment completed
- Automation for workload deployment started
- Image repository creation progressed
// Blockers
a|
- Groups for RBAC not defined in Active Directory discovered


// Date
| 06/06/2021

// Activities
a|
- Automation for workload deployment progressed
- Image repository creation completed

// Blockers
a|
- Groups for RBAC not defined in Active Directory resolved
- No Internet access for Satellite to pull in images from CDN discovered

|===


////

[cols="1,5,5",options=header]
|===
|Date
|Activities
|Blockers/Next Plan

// Date
| 12/17/2020

// Activities
a|
- Managed establishing connection to "bu-21-7" node "Petitboot" bootloader.
- Received RHCOS & RHEL PPC images.
- Tried provisioning RHEL & RHCOS OS via a TFTP server we created which been uploaded with the RHEL & RHCOS Images.
- Manually configuring the BMC node IP to the subnet on the Foreman server

// Blockers/Next Plan
a|
- Tried provisioning either one of the mentioned images through the Petitboot URL option - this did not succeed
- Tried to install RHCOS with Naved, once by using the Formen web UI and second by running a python server publishing the relevant files from the iso image - this did not scceed
- The node is trying to complete a DHCP request on port 67 on the Foreman
- Naved states that DHCP should be served from the Foreman service and we should look into it.

// Date
| 22/17/2020

// Activities
a|
- Provisioned RHEL 8.3 on the node bu-21-7 but with an Livecd

// Blockers/Next Plan
a|
- Trying to find a way to install the OS on the kernel.

|===
